### ISSUE TITLE
Test model eos9taz

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9taz#1]
Hi!

Can you please test the model eos9taz incorporated by Anamika on the Colab and CLI? Thanks!

**Comment by DhanshreeA** [comment]
On CLI I am getting an install error while fetching this model:
```python
15:40:13 | DEBUG    | Error occurred while running: bash /tmp/ersilia-8zc7qon5/script.sh > /tmp/ersilia-_yta2ca1/command_outputs.log 2>&1
15:40:13 | ERROR    | Ersilia exception class:
ModelPackageInstallError

```
However within the log file at tmp/ersilia-_yta2ca1/command_outputs.log I don't see any package that failed during install. All the packages specified in the /tmp/ersilia-8zc7qon5/script.sh are installed it seems.

**Comment by GemmaTuron** [comment]
Thanks  @DhanshreeA, the automated workflow test also failed at the same point. @anamika-yadav99 please can you have a look and confirm this model was working in your system and whether it is still working?

**Comment by anamika-yadav99** [comment]
Hi @Gemma! It works in my system. Something similar happened earlier as well. I wasn't able to reproduce the error but after comparing the script.sh file where the model fails in the workflow, I found out that in the failed fetch script.sh looks like

![image](https://user-images.githubusercontent.com/54634163/214682558-1829817f-f374-49dc-99d1-0c2dfd6ddefc.png)


 but in my local it looks like: 
![image](https://user-images.githubusercontent.com/54634163/214682315-b7dd8f6e-7ae8-4769-a3eb-de8ab02f8bbb.png)

I tried to figure out why this happens but later on Miquel was able to fetch it and I thought maybe it works now.

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

What do you suggest here then? We need to make sure the model works consistently

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

The model failed at fetching on colab. 
It gives the same error as with @DhanshreeA 's test.

Error message:

Ersilia exception class:
ModelPackageInstallError

Detailed error:
Error occured while installing package by running "bash /tmp/ersilia-21od526s/script.sh > /tmp/ersilia-i_o384zg/command_outputs.log 2>&1" command

https://colab.research.google.com/drive/1A7_s8yWn93xfBOp-7kJsU7tfDMk0QEgX#scrollTo=GvlE-AuKWLd0

On my CLI, it is giving an EmptyOutputError:
[eos9taz.log](https://github.com/ersilia-os/eos9taz/files/10527020/eos9taz.log)

**Comment by GemmaTuron** [comment]
Hello @Femme-js 
As we have discussed before, the empty output error is just the final outcome, you should try to read through your log file to identify which is the origin of the error, and compare it to the above errors to see if we are all talking about the same issue.

**Comment by anamika-yadav99** [comment]
> Hi @anamika-yadav99
> 
> What do you suggest here then? We need to make sure the model works consistently

Hi @Gemma I'm not able to reproduce the error that's why I have some trouble fixing it. I'll delete the ersilia and all the environment and try it again. Is it okay if I do this on Wednesday?

**Comment by Femme-js** [comment]
Hi @GemmaTuron ! I have reproduced the same error as @DhanshreeA 's.

[eos9taz.log](https://github.com/ersilia-os/eos9taz/files/10529880/eos9taz.log)

However, I am not getting output in /tmp folder. I can't understand the reason behind it.

**Comment by GemmaTuron** [comment]
Thanks @DhanshreeA , @anamika-yadav99 and @Femme-js 

What do we do in this case? Well, this error seems difficult to debug from the ersilia cli since there is not much information (just for consistency, I've also tried with the same error log). What can we do then?
We need to first check the model is working. Like you do when you incorporate a model you can:

1.  clone the github repo (check if everything is being downloaded as expected)
2. Create a conda environment with the requirements (make sure no dependency issues arise)
3. Manually run the main.py
4. Try out the --repo-path flag
This should give enough information to pinpoint the error cause.

@anamika-yadav99 sure about Wednesday I know you are busy finishing the project this week

**Comment by GemmaTuron** [comment]
Hello @anamika-yadav99 

Could you have a look at this please?

**Comment by anamika-yadav99** [comment]
Hi @Gemma ! I'm sorry I couldn't look into this earlier. The issue with this model runs much deep and I feel it wouldn't make sense to fix it as this is not a predictive model. We are already including it in chem-sampler where it's faster and does a much better job. This model in the model hub wouldn't be very practical either as it takes long time to generate enough molecules to sample something similar to input molecule. My suggestion would be drop it from the hub. What do you think?

**Comment by DhanshreeA** [comment]
A quick update: I had tried running the model locally by cloning the repo and using the repo-path flag, and the installation is running into the same issues as above. I haven't tested it further.

**Comment by anamika-yadav99** [comment]
Hi @DhanshreeA that's because conda fails to resolve for rdkit. If you install rdkit using channel rdkit. Also, there was a typo in dockerfile. I fixed it but after that bentoml serve fails with internal error 500. Probably, something has changed with API.

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

The uses of models within the Ersilia model hub and other packages like the chem-sampler are very different. Chem-sampler will mostly be used by ersilia and advanced collaborators, whereas the models in the hub are designed to be easier and more straightforward to use. I would not drop it from there hence, you might have noticed we do not only have predictive models but also generative, representation models etc
Can you explain what you mean by _The issue with this model runs much deep_ and what are the steps to solve it?

**Comment by DhanshreeA** [comment]
> Hi @DhanshreeA that's because conda fails to resolve for rdkit. If you install rdkit using channel rdkit. Also, there was a typo in dockerfile. I fixed it but after that bentoml serve fails with internal error 500. Probably, something has changed with API. 

Hi @anamika-yadav99 For the BentoML server crash, we can look at the logs generated in tmp files by the ersilia CLI. Hopefully it should be straightforward.

If with the Dockerfile fix you've been able to get the model to an installable state, you could push those changes to your fork, and I can clone that and figure out the API error.

**Comment by anamika-yadav99** [comment]
Hi @DhanshreeA  and @Femme-js can you try fetching eos9taz again? It'll might take a little longer because generating molecules on cpu is slower.

**Comment by DhanshreeA** [comment]
Hi @anamika-yadav99 I can fetch it now! :tada: and I tried running it with a few inputs and can confirm that it works on my local with the ersilia cli.

[eos9taz_output_5.csv](https://github.com/ersilia-os/eos9taz/files/10685261/eos9taz_output_5.csv)

**However** It is producing an inconsistent number of outputs on Colab: https://colab.research.google.com/drive/1fw1ADgwLe0691uuyGRhsTEK3aFfqhMSs?usp=sharing

I am testing it with all the 442 compounds on Colab however, it's generating results for only five.

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron ci test still fails with empty output error. Not sure why that's happening.

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 !

Thanks for solving this issue, I've also tested the model and it works fine. Can you briefly explain what changes did you make, so that we have record of it?
As for the git action test do not worry, it is a reported issue with git lfs and we are working to solve it as fast as we can!

**Comment by anamika-yadav99** [comment]
I removed all.the dependencies from the dockerfile and instead pip installed molecule generation. Installations were leading to the version conflicts and were automatically updating other libraries which lead to rdkit error. It looked like there was something wrong with the pickled file. But fortunately, it wasn't.
