### ISSUE TITLE
Interpretation field wrong

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos9taz#2]
Hi @anamika-yadav99 !

I've noticed that in the metadata.json file (and therefore README and Airtable), the interpretation seems it was "copied" (probably a typing error on my end) from another completely different model. The interpretation should be something like "XXX new generated compounds" --> is it always a fixed number?
If you can refine this sentence and edit the "interpretation" field in the metadata.json, I'd be super grateful.

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron ! I have updated it but can you try the model and let me know if I should change the output format. Atm it takes a smile as input and generates a 1000 molecules and then returns 100 most similar molecules.  Ersilia model hub only let's smile strings as input which limits the capability to input the number of smiles to generate.

**Comment by GemmaTuron** [comment]
Thanks @anamika-yadav99 !

This sounds perfect to help users understand what is going on
